name: Build and Upload Executable

on:
  push:
    tags:
      - '*'

jobs:
  build-and-upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Install Conan
        run: pip install conan

      - name: Cache Conan dependencies
        id: cache-conan
        uses: actions/cache@v4
        with:
          path: ~/.conan2
          key: ${{ runner.os }}-conan-${{ hashFiles('conanfile.txt') }}

      - name: Create default Conan profile
        if: steps.cache-conan.outputs.cache-hit != 'true'
        run: conan profile detect --force

      - name: Install dependencies
        run: conan install . --output-folder=build --build=missing -s build_type=Release

      - name: Configure CMake
        run: |
          cd build
          cmake .. -G "Unix Makefiles" -DCMAKE_TOOLCHAIN_FILE="conan_toolchain.cmake" -DCMAKE_BUILD_TYPE="Release"
        shell: bash

      - name: Build vex target
        run: make -C build vex -j4

      - name: Upload vex executable to release (Linux)
        if: runner.os == 'Linux'
        uses: softprops/action-gh-release@v2
        with:
          files: build/vex
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload vex executable to release (Windows)
        if: runner.os == 'Windows'
        uses: softprops/action-gh-release@v2
        with:
          files: build/Release/vex.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
